# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "about/about/index.html"
  weight = 20

[[main]]
  name = "Blog"
  url = "index.html#posts"
  weight = 20

#[[main]]
  #name = "Projects"
  #url = "index.html#projects"
  #weight = 30

[[main]]
  name = "Publications"
  url = "index.html#publications"
  weight = 40


[[main]]
  name = "Contact"
  url = "index.html#contact"
  weight = 60
  

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
    name = "CV"
    url = "files/Casar_CV_May2020.pdf"
    weight = 70
